<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(2,1,1,'5Y2V5bGC5rS75Yqo5oi/');
$cfg_Cs[4]=array(2,1,1,'5Y+M5bGC5rS75Yqo5oi/');
$cfg_Cs[5]=array(2,1,1,'5bKp5qOJ5aSN5ZCI5p2/');
$cfg_Cs[6]=array(2,1,1,'6Ziz5YWJ5oi/57O75YiX');
$cfg_Cs[7]=array(2,1,1,'5pat5qGl6ZOd57O75YiX');
$cfg_Cs[8]=array(2,1,1,'5YW25LuW5YiG57G7');
$cfg_Cs[9]=array(0,1,1,'6LWE6LSo6I2j6KqJ');
$cfg_Cs[10]=array(0,1,1,'5bel6Im65rWB56iL');
$cfg_Cs[11]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[12]=array(0,1,1,'5bel56iL5qGI5L6L');
$cfg_Cs[13]=array(0,1,1,'5oqA5pyv5Zut5Zyw');
$cfg_Cs[14]=array(0,1,1,'6IGU57O75pa55byP');
?>