<li>
            <div class="prod7-left"> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]"/></a>
               <p class="prod-zoom"></p>
             </div>
            <p> <a href="[field:arcurl/]" title="[field:title/]" class="pg-color">[field:title/]</a> <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> </p>
            <div class="prod7-right">[field:description function="cn_substr(@me,200)"/]...</div>
          </li>