<?php
$z[0]=Array("arcurl","",52,67);
$z[1]=Array("title","",76,90);
$z[2]=Array("picname","",102,118);
$z[3]=Array("title","",125,139);
$z[4]=Array("arcurl","",236,251);
$z[5]=Array("title","",260,274);
$z[6]=Array("title","",293,307);
$z[7]=Array("pubdate","",318,365);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("description","",416,466);
$z[8][4]['function']="cn_substr(@me,200)";

?>