<li><a href="[field:arcurl/]" title="[field:title/]"> <img class="pimg" src="[field:picname/]" alt="[field:title/]" width="120" height="90" />
          <div class="newsli_r">
            <p class="newsli_rt"><span class="fl">[field:title/]</span></p>
            <label>点击量：[field:click/]次</label>
            <p class="newscontent">　[field:info/]...　</p>
          </div>
          </a> </li>