<li>
              <div class="xin"> <a class="img" href="[field:arcurl/]" title=""><img src="[field:picname/]" alt="[field:title/]" width="178" height="133" /></a>
                <div class="xinright"> <a class="name" href="/index.php/cn/Honor/view/id/79.html" title="[field:title/]">[field:title/]</a> <a href="[field:arcurl/]" title="[field:title/]" class="con">　　[field:info/]...　</a> <a  href="[field:arcurl/]" class="more" title="查看更多">查看更多</a> </div>
              </div>
            </li>