<?php
$z[0]=Array("flink","  [field:link /]  ",120,198);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("channel"," <a title=\"[field:typename/]\" href=\"[field:typeurl/]\">[field:typename/]</a> ",506,622);
$z[1][4]['type']="top";
$z[2]=Array("global","",777,803);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",936,960);
$z[3][4]['name']="cfg_beian";

?>