<?php
$z[0]=Array("global","",116,142);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",189,215);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n        <li> <a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n          <div class=\"nav_dd dn\"> {dede:channel type='son' noself='yes'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </div>\r\n        </li>\r\n        ",465,843);
$z[2][4]['typeid']="top";
$z[3]=Array("global","",1238,1263);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channelartlist","\r\n          {dede:type}  \r\n            \r\n            \r\n            \r\n            \r\n            \r\n            \r\n            <option value='[field:id/]' >[field:typename/]</option>\r\n            \r\n            \r\n            \r\n            \r\n            \r\n            \r\n            {/dede:type} \r\n          ",1839,2197);
$z[4][4]['typeid']="top";
$z[5]=Array("arclist","\r\n            <li><a target=\"_parent\" href=\"[field:arcurl/]\" title=\"[field:title/]\"><span>[field:title/]</span>\r\n              <label> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</label>\r\n              </a></li>\r\n            ",2989,3299);
$z[5][4]['typeid']="11";
$z[5][4]['row']="3";
$z[5][4]['titlelen']="50";
$z[5][4]['orderby']="pubdate";

?>