<?php
$z[0]=Array("channel","\r\n        <li id=\"2\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",236,488);
$z[0][4]['type']="son";
$z[0][4]['typeid']="2";
$z[0][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[1]=Array("arclist","\r\n          <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> </li>\r\n          ",855,1038);
$z[1][4]['typeid']="13";
$z[1][4]['row']="5";
$z[1][4]['titlelen']="30";
$z[1][4]['orderby']="pubdate";

?>